### ISSUE TITLE
Lien dans le footer trop grand

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#78]
![image](https://cloud.githubusercontent.com/assets/12863317/20539519/95e545d8-b0f5-11e6-8dc2-e716f3cfc1d2.png)

Simple fix:
```css
#footer a:first-child {
    display: table-cell;
}
```
