### ISSUE TITLE
Popup BR - Un seul des coins est arrondi

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars-client#84]
![image](https://cloud.githubusercontent.com/assets/12863317/20813366/a00138ca-b815-11e6-913d-978deedd3e46.png)
Seul le coin supérieur gauche est arrondi alors que les autres non.

**Comment by Becold** [comment]
Fix possible : 

```css
.popup battle_royale_popup {
    border-radius: 3px;
}

.popup battle_royale_popup .title .options .option.dismiss {
    border-top-right-radius: 3px;
}
```
